trigger:
- main  # Trigger on changes to the main branch

pool:
  name: RaspberryPi4  # Use the Raspberry Pi self-hosted agent

steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '3.x'
#     addToPath: true

- script: |
    # Install dependencies
    pip install -r requirements.txt
    pip install python-dotenv

    # Set up the Edge Impulse CLI
    python src/main.py setup --project_id $(EI_PROJECT_ID) --api_key $(EI_API_KEY) --deploy_type $(DEPLOY_TYPE)
  displayName: "Setup Edge Impulse CLI"

- script: |
    # Build the model
    JOB_ID=$(python src/main.py build | grep -oP '(?<=Job ID: )\w+')
    echo "##vso[task.setvariable variable=JOB_ID]$JOB_ID"
  displayName: "Build Model"

- script: |
    # Wait for job completion
    python src/main.py wait_for_job_completion --job_id $(JOB_ID)
  displayName: "Wait for Job Completion"

- script: |
    # Deploy the model
    python src/main.py deploy_model
  displayName: "Deploy Model"